"""Structural patterns banned in assistant output, independent of language.

Standard library only. Regexes are compiled at import time, not at call time.
"""

import re
from typing import Dict, Pattern

BANNED: Dict[str, Pattern[str]] = {
    # A URL, phone number or email is never generated by the intake assistant.
    "contains_url": re.compile(r"https?://|www\.", re.IGNORECASE),
    "contains_email": re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+"),
    # Checked before contains_phone: a bare 12-digit run is an identifier, not
    # a dialled number, and the phone pattern would otherwise claim it first.
    "contains_long_id": re.compile(r"(?<!\d)\d{9,}(?!\d)"),
    "contains_phone": re.compile(r"(?<!\d)(?:\+?\d[\d\s-]{7,}\d)(?!\d)"),
    # The assistant states no numeric certainty to the victim.
    "contains_percentage": re.compile(r"\d+\s?%"),
    # Assessment vocabulary must never reach a victim-facing sentence.
    "leaks_assessment": re.compile(
        r"\b(svi|risk band|risk score|vulnerability index|dimension d[1-9]|"
        r"confidence score|assessment score|critical band|priority score)\b",
        re.IGNORECASE,
    ),
    # Markup or template residue from a model.
    "contains_markup": re.compile(r"<[^>]+>|\{\{|\}\}|\[\[|\]\]"),
    # A model that started listing is no longer asking one question.
    "contains_list": re.compile(r"(^|\n)\s*(\d+[.)]|[-*•])\s+"),
}
