/**
 * Typed mirror of docs/contracts/CONTRACTS.md.
 *
 * This file is generated by hand and reviewed alongside the contract. Changing
 * it without a `type:contract` issue and the leads' approval is contract
 * drift. No `any` is permitted on a contract shape.
 *
 * Contract v4 (2026-09-13): PC-01..PC-12 decisions applied.
 */

/* -------------------------------------------------------------------------
 * Section 9 — frozen enumerations (PC-10). Mirrors backend/app/core/enums.py;
 * backend/tests/test_contract_mirror.py checks the arrays below.
 * ---------------------------------------------------------------------- */

export const SESSION_CHANNELS = ["mobile_voice", "mobile_chat", "portal_chat", "upload"] as const;
export const TEXT_CHANNELS = ["mobile_chat", "portal_chat"] as const;
export const SESSION_STATES = [
  "S0", "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "SX", "SH",
] as const;
export const CONSENT_STATUSES = ["granted", "declined", "pending"] as const;
export const CASE_STATUSES = ["open", "claimed", "taken_over", "closed"] as const;
export const BANDS = ["Low", "Moderate", "High", "Critical"] as const;
export const ALERT_TYPES = ["crisis", "threat", "medical", "coercion"] as const;
export const ALERT_SEVERITIES = ["high", "critical"] as const;
export const RECOMMENDATION_PATHWAYS = [
  "counselling", "legal_aid", "medical", "police", "witness_protection",
  "emergency", "welfare", "follow_up",
] as const;
export const DECISIONS = ["confirm", "modify", "reject"] as const;
export const ROLES = ["victim", "executive", "supervisor"] as const;
export const TIMELINE_STAGES = [
  "request_received", "under_review", "officer_assigned",
  "action_taken", "follow_up_scheduled", "closed",
] as const;
export const TURN_SPEAKERS = ["victim", "assistant", "officer"] as const;

export type Lang = "hi" | "en";
export type SessionChannel = (typeof SESSION_CHANNELS)[number];
export type SessionState = (typeof SESSION_STATES)[number];
export type ConsentStatus = (typeof CONSENT_STATUSES)[number];
export type CaseStatus = (typeof CASE_STATUSES)[number];
export type Band = (typeof BANDS)[number];
export type AlertType = (typeof ALERT_TYPES)[number];
export type AlertSeverity = (typeof ALERT_SEVERITIES)[number];
export type RecommendationPathway = (typeof RECOMMENDATION_PATHWAYS)[number];
export type Role = (typeof ROLES)[number];
export type DecisionKind = (typeof DECISIONS)[number];
export type TimelineStage = (typeof TIMELINE_STAGES)[number];
export type TurnSpeaker = (typeof TURN_SPEAKERS)[number];

/** Every non-2xx body. 422 carries [{loc, msg}]; 500 is "Internal error". */
export interface ErrorResponse {
  detail: string | { loc: (string | number)[]; msg: string }[];
}

/* -------------------------------------------------------------------------
 * Section 2 — events a victim client MAY receive.
 * The console receives these too, as the two-sided transcript.
 * ---------------------------------------------------------------------- */

/** PC-12: "none" is text only and makes no audio-availability claim. */
export const ASSISTANT_AUDIO = ["none", "streaming", "prerecorded"] as const;
export type AssistantAudio = (typeof ASSISTANT_AUDIO)[number];

export interface AssistantTurn {
  turn_id: string;
  text: string;
  lang: Lang;
  intent: string;
  audio: AssistantAudio;
}

export interface TranscriptLine {
  turn_id: string;
  speaker: "victim" | "assistant";
  text: string;
  lang: Lang;
  ts: string;
}

export interface SessionStatus {
  state: SessionState;
  consent: ConsentStatus;
  lang: Lang;
  human_joined: boolean;
}

export interface TimelineUpdate {
  stage: TimelineStage;
  label: string;
  ts: string;
}

/** PC-07: typed by the human officer after takeover. No assessment field. */
export interface OfficerMessage {
  turn_id: string;
  text: string;
  lang: Lang;
  ts: string;
  origin: "human_officer";
}

/* -------------------------------------------------------------------------
 * Section 3 — EXECUTIVE CONSOLE ONLY.
 * Enforced server-side by role on the socket. These types exist in the console
 * and must never be imported by mobile/.
 * ---------------------------------------------------------------------- */

export type DimensionId = "D1" | "D2" | "D3" | "D4" | "D5" | "D6" | "D7" | "D8" | "D9";

export interface DimensionValue {
  /** null when the dimension is unscored (e.g. D4 on the text channel). */
  score: number | null;
  conf: number | null;
  evidence_turn_ids: string[];
}

export interface DimensionUpdate {
  dims: Record<DimensionId, DimensionValue>;
  /** null when the engine abstained. Never render a score without its breakdown. */
  svi: number | null;
  band: Band | null;
  needs_human: boolean;
  overrides_applied: string[];
}

/**
 * PC-02 (frozen): the alert kind is `alert_type`. The envelope's `type` is
 * always the event name and payload content can never overwrite it.
 */
export interface SafetyAlert {
  alert_type: AlertType;
  severity: AlertSeverity;
  evidence_turn_ids: string[];
  requires_ack: true;
}

export interface CaseStructured {
  incident: string | null;
  timeline: Array<{ stage: string; label: string; ts: string }>;
  persons: string[];
  threats: string[];
  safety_now: string | null;
  medical_need: string | null;
  legal_status: string | null;
  isolation: string | null;
  requested_support: string | null;
}

/** An AI recommendation. It has no decision field: a human decides. */
export interface ActionRecommended {
  action_id: string;
  action_type: string;
  rationale: string;
  policy_citations: string[];
  confidence: number;
}

export interface SafeSignalFlag {
  direction: "up" | "down";
  delta: number;
  suggested_question: string;
}

export interface EscalationPacket {
  case_id: string;
  band: Band | null;
  alerts: SafetyAlert[];
  summary: string;
  ready: boolean;
}

/* -------------------------------------------------------------------------
 * Discriminated union of everything that arrives on the socket.
 * ---------------------------------------------------------------------- */

export type VictimEvent =
  | ({ type: "assistant.turn" } & AssistantTurn)
  | ({ type: "transcript.line" } & TranscriptLine)
  | ({ type: "session.status" } & SessionStatus)
  | ({ type: "timeline.update" } & TimelineUpdate)
  | ({ type: "officer.message" } & OfficerMessage);

export type ExecutiveEvent =
  | ({ type: "dimension.update" } & DimensionUpdate)
  | ({ type: "alert.safety" } & SafetyAlert)
  | ({ type: "case.structured" } & CaseStructured)
  | ({ type: "action.recommended" } & ActionRecommended)
  | ({ type: "safesignal.flag" } & SafeSignalFlag)
  | ({ type: "escalation.packet" } & EscalationPacket);

export type SocketEvent = VictimEvent | ExecutiveEvent;

export interface SocketAuth {
  type: "auth";
  token: string;
}
export interface SocketAuthOk {
  type: "auth.ok";
  session_id: string;
  role: Role;
}
export interface ChatMessageRequest {
  type: "chat.message";
  client_message_id: string;
  text: string;
  lang: Lang;
}
export type ChatAck =
  | { type: "chat.ack"; client_message_id: string; status: "accepted" | "duplicate"; turn_id: string }
  | { type: "chat.ack"; client_message_id: string; status: "rejected"; error: "session_ended" | "not_permitted" | "id_conflict" };
export interface HumanRequest {
  type: "request_human";
  request_id: string;
}
export type HumanRequestAck =
  | { type: "human_request.ack"; request_id: string; status: "accepted" | "duplicate" }
  | { type: "human_request.ack"; request_id: string; status: "rejected"; error: "session_ended" | "not_permitted" };
export type SocketControlFrame = SocketAuthOk | ChatAck | HumanRequestAck;

/** Event names a victim client may receive. Mirrors backend/app/ws/events.py. */
export const VICTIM_ALLOWED_EVENTS = [
  "assistant.turn",
  "transcript.line",
  "session.status",
  "timeline.update",
  "officer.message",
] as const;

export const EXECUTIVE_ONLY_EVENTS = [
  "dimension.update",
  "alert.safety",
  "case.structured",
  "action.recommended",
  "safesignal.flag",
  "escalation.packet",
] as const;

/* -------------------------------------------------------------------------
 * Section 4 — REST bodies.
 * ---------------------------------------------------------------------- */

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  token: string;
  role: Role;
  display_name: string;
}

export interface DecisionRequest {
  action_id: string;
  decision: DecisionKind;
  /** Required for modify and reject; the server returns 400 without it. */
  rationale?: string;
  /** Optional; when sent it must equal the signed-in officer. */
  officer_id?: string;
}

/** POST /sessions (PC-09, frozen). */
export interface CreateSessionRequest {
  channel: SessionChannel;
  consent: ConsentStatus;
  lang: Lang;
}

/**
 * POST /sessions response (PC-09, frozen). `session_token` is the VICTIM
 * credential, scoped to this one session; it never authorises a console
 * route. `ws_url` is a path with no token (see CONTRACTS.md section 1).
 */
export interface CreateSessionResponse {
  session_id: string;
  case_id: string;
  reference_no: string;
  session_token: string;
  ws_url: string;
  lang: Lang;
  consent: ConsentStatus;
  ai_disclosure: string;
  human_request_available: boolean;
}

/** POST /cases/{id}/alerts/{alert_id}/ack (PC-01, frozen). Idempotent. */
export interface AlertAckResponse {
  alert_id: string;
  case_id: string;
  acknowledged_by: string;
  acknowledged_at: string;
}

/** POST /cases/{id}/messages (PC-07, frozen). Only after takeover. */
export interface OfficerMessageRequest {
  text: string;
  lang?: Lang;
}

export interface OfficerMessageResponse {
  turn_id: string;
  case_id: string;
  origin: "human_officer";
  ts: string;
}

/** reason is REQUIRED by contract and enforced server-side. */
export interface OverrideRequest {
  band: Band;
  reason: string;
}

/** GET /cases/{id}/timeline — victim-safe, contains no assessment field. */
export interface VictimTimeline {
  reference: string;
  timeline: TimelineUpdate[];
}

/* -------------------------------------------------------------------------
 * Section 7 — SVI. Weights are provisional, pending expert calibration, and
 * the console must label them that way.
 * ---------------------------------------------------------------------- */

export const DIMENSION_WEIGHTS: Record<DimensionId, number> = {
  D1: 0.22,
  D2: 0.18,
  D3: 0.13,
  D4: 0.12,
  D5: 0.08,
  D6: 0.08,
  D7: 0.08,
  D8: 0.06,
  D9: 0.05,
};

export const DIMENSION_LABELS: Record<DimensionId, string> = {
  D1: "Immediate safety threat",
  D2: "Crisis / self-harm language",
  D3: "Fear, intimidation, threats",
  D4: "Acute distress (acoustic + emotional)",
  D5: "Trauma-associated indicators",
  D6: "Social isolation, boycott, displacement",
  D7: "Medical urgency",
  D8: "Legal urgency",
  D9: "Communication safety",
};

export const WEIGHTS_ARE_PROVISIONAL = true;

/** PC-08: with only D4 structurally unavailable, weights sum to this. */
export const TEXT_CHANNEL_WEIGHT_DENOMINATOR = 0.88;

/** Shown on every screen carrying an assessment. Judges photograph screens. */
export const ASSESSMENT_DISCLAIMER =
  "This assessment is an assistive prioritisation aid generated by an AI system. " +
  "It is not a clinical, legal or forensic determination. All decisions rest with " +
  "the reviewing officer.";
