/**
 * Typed mirror of docs/contracts/CONTRACTS.md.
 *
 * This file is generated by hand and reviewed alongside the contract. Changing
 * it without a `type:contract` issue and three lead approvals is contract
 * drift. No `any` is permitted on a contract shape.
 */

export type Lang = "hi" | "en";
export type Band = "Low" | "Moderate" | "High" | "Critical";
export type Role = "victim" | "executive" | "supervisor";
export type DecisionKind = "confirm" | "modify" | "reject";

/* -------------------------------------------------------------------------
 * Section 2 — events a victim client MAY receive.
 * The console receives these too, as the two-sided transcript.
 * ---------------------------------------------------------------------- */

export interface AssistantTurn {
  turn_id: string;
  text: string;
  lang: Lang;
  intent: string;
  audio: "streaming" | "prerecorded";
}

export interface TranscriptLine {
  turn_id: string;
  speaker: "victim" | "assistant";
  text: string;
  lang: Lang;
  ts: string;
}

export interface SessionStatus {
  state: string;
  consent: string;
  lang: Lang;
  human_joined: boolean;
}

export interface TimelineUpdate {
  stage: string;
  label: string;
  ts: string;
}

/* -------------------------------------------------------------------------
 * Section 3 — EXECUTIVE CONSOLE ONLY.
 * Enforced server-side by role on the socket. These types exist in the console
 * and must never be imported by mobile/.
 * ---------------------------------------------------------------------- */

export type DimensionId = "D1" | "D2" | "D3" | "D4" | "D5" | "D6" | "D7" | "D8" | "D9";

export interface DimensionValue {
  score: number;
  conf: number;
  evidence_turn_ids: string[];
}

export interface DimensionUpdate {
  dims: Record<DimensionId, DimensionValue>;
  /** null when the engine abstained. Never render a score without its breakdown. */
  svi: number | null;
  band: Band | null;
  needs_human: boolean;
  overrides_applied: string[];
}

export interface SafetyAlert {
  type: "crisis" | "threat" | "medical" | "coercion";
  severity: string;
  evidence_turn_ids: string[];
  requires_ack: true;
}

export interface CaseStructured {
  incident: string | null;
  timeline: TimelineUpdate[];
  persons: string[];
  threats: string[];
  safety_now: string | null;
  medical_need: string | null;
  legal_status: string | null;
  isolation: string | null;
  requested_support: string | null;
}

/** An AI recommendation. It has no decision field: a human decides. */
export interface ActionRecommended {
  action_id: string;
  action_type: string;
  rationale: string;
  policy_citations: string[];
  confidence: number;
  status: "awaiting_decision" | "decided";
}

export interface SafeSignalFlag {
  direction: "up" | "down";
  delta: number;
  suggested_question: string;
}

export interface EscalationPacket {
  case_id: string;
  band: Band | null;
  alerts: SafetyAlert[];
  summary: string;
  ready: boolean;
}

/* -------------------------------------------------------------------------
 * Discriminated union of everything that arrives on the socket.
 * ---------------------------------------------------------------------- */

export type VictimEvent =
  | ({ type: "assistant.turn" } & AssistantTurn)
  | ({ type: "transcript.line" } & TranscriptLine)
  | ({ type: "session.status" } & SessionStatus)
  | ({ type: "timeline.update" } & TimelineUpdate);

export type ExecutiveEvent =
  | ({ type: "dimension.update" } & DimensionUpdate)
  | ({ type: "alert.safety" } & SafetyAlert)
  | ({ type: "case.structured" } & CaseStructured)
  | ({ type: "action.recommended" } & ActionRecommended)
  | ({ type: "safesignal.flag" } & SafeSignalFlag)
  | ({ type: "escalation.packet" } & EscalationPacket);

export type SocketEvent = VictimEvent | ExecutiveEvent;

/** Event names a victim client may receive. Mirrors backend/app/ws/events.py. */
export const VICTIM_ALLOWED_EVENTS = [
  "assistant.turn",
  "transcript.line",
  "session.status",
  "timeline.update",
] as const;

export const EXECUTIVE_ONLY_EVENTS = [
  "dimension.update",
  "alert.safety",
  "case.structured",
  "action.recommended",
  "safesignal.flag",
  "escalation.packet",
] as const;

/* -------------------------------------------------------------------------
 * Section 4 — REST bodies.
 * ---------------------------------------------------------------------- */

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  token: string;
  role: Role;
  display_name: string;
}

export interface DecisionRequest {
  action_id: string;
  decision: DecisionKind;
  rationale: string;
  officer_id: string;
}

/** reason is REQUIRED by contract and enforced server-side. */
export interface OverrideRequest {
  band: Band;
  reason: string;
}

/** GET /cases/{id}/timeline — victim-safe, contains no assessment field. */
export interface VictimTimeline {
  reference: string;
  timeline: TimelineUpdate[];
}

/* -------------------------------------------------------------------------
 * Section 7 — SVI. Weights are provisional, pending expert calibration, and
 * the console must label them that way.
 * ---------------------------------------------------------------------- */

export const DIMENSION_WEIGHTS: Record<DimensionId, number> = {
  D1: 0.22,
  D2: 0.18,
  D3: 0.13,
  D4: 0.12,
  D5: 0.08,
  D6: 0.08,
  D7: 0.08,
  D8: 0.06,
  D9: 0.05,
};

export const DIMENSION_LABELS: Record<DimensionId, string> = {
  D1: "Immediate safety threat",
  D2: "Crisis / self-harm language",
  D3: "Fear, intimidation, threats",
  D4: "Acute distress (acoustic + emotional)",
  D5: "Trauma-associated indicators",
  D6: "Social isolation, boycott, displacement",
  D7: "Medical urgency",
  D8: "Legal urgency",
  D9: "Communication safety",
};

export const WEIGHTS_ARE_PROVISIONAL = true;

/** Shown on every screen carrying an assessment. Judges photograph screens. */
export const ASSESSMENT_DISCLAIMER =
  "This assessment is an assistive prioritisation aid generated by an AI system. " +
  "It is not a clinical, legal or forensic determination. All decisions rest with " +
  "the reviewing officer.";
