<#
.SYNOPSIS
    Recreate the local SQLite database from migrations and the deterministic seed.

.DESCRIPTION
    Local development data only. Everything this deletes is regenerated by
    `alembic upgrade head` plus `backend/seed/seed.py`.

    Refuses to touch anything outside the ignored runtime directory, so it
    cannot be pointed at a database that is not disposable.

.PARAMETER Database
    Path to the SQLite file. Defaults to runtime/db/sahay.db. Must live under
    runtime/.

.PARAMETER Force
    Skip the confirmation prompt. Required for non-interactive use; without it
    the script prompts and a redirected stdin would hang.
#>
[CmdletBinding()]
param(
    [string]$Database,
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$python = Join-Path $root "backend\.venv\Scripts\python.exe"

if (-not (Test-Path $python)) {
    throw "backend/.venv is missing. EXT-001 must be approved and installed first."
}

$runtimeDb = Join-Path $root "runtime\db"
if (-not $Database) { $Database = Join-Path $runtimeDb "sahay.db" }
$Database = [System.IO.Path]::GetFullPath($Database)

# Guard: only ever delete inside runtime/, which is git-ignored and disposable.
if (-not $Database.StartsWith([System.IO.Path]::GetFullPath($runtimeDb), [StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to reset '$Database'. Only databases under runtime/db are disposable."
}

Write-Host "Target database: $Database"
Write-Host "This deletes that file and its -wal/-shm siblings, then reruns migrations and the seed."

if (-not $Force) {
    $answer = Read-Host "Type RESET to continue (or re-run with -Force)"
    if ($answer -ne "RESET") { Write-Host "Cancelled."; exit 1 }
}

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Database) | Out-Null
foreach ($suffix in @("", "-wal", "-shm", "-journal")) {
    $path = "$Database$suffix"
    if (Test-Path $path) { Remove-Item $path -Force; Write-Host "  removed $(Split-Path -Leaf $path)" }
}

# Both steps read DATABASE_URL, so a non-default -Database is honoured.
$uri = "sqlite+aiosqlite:///" + ($Database -replace '\\', '/')
$env:DATABASE_URL = $uri

Push-Location (Join-Path $root "backend")
try {
    & $python -m alembic upgrade head
    if ($LASTEXITCODE -ne 0) { throw "alembic upgrade failed" }
}
finally { Pop-Location }

& $python (Join-Path $root "backend\seed\seed.py") --reset
if ($LASTEXITCODE -ne 0) { throw "seed failed" }

Write-Host "Local database reset and reseeded."
